# Generated by Django 4.2.6 on 2023-11-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changeRequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayofftrading',
            name='supervisor_approval_status',
            field=models.CharField(blank=True, choices=[('', '----'), ('approved', 'Approved'), ('rejected', 'Rejected')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dayofftrading',
            name='trading_status',
            field=models.CharField(choices=[('', '----'), ('in process', 'In Process'), ('approved', 'Approved'), ('rejected', 'Rejected')], default=None, max_length=50),
        ),
    ]
