# Generated by Django 4.2.6 on 2024-01-31 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_employee_supervisor_1_and_more'),
        ('changeRequest', '0004_shifttimetrading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayofftrading',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dayOffTradingSupervisor', to='accounts.employee'),
        ),
    ]
