# Generated by Django 4.2.6 on 2024-01-09 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_updated_by_employee_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='supervisor_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor1', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='supervisor_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor2', to='accounts.employee'),
        ),
    ]
