# Generated by Django 4.2.6 on 2024-02-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='avaya_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='doj',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='vdi',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
