# Generated by Django 4.2.6 on 2024-05-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_employee_is_absent'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_previously_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
