# Generated by Django 4.2.6 on 2024-05-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_employee_is_previously_logged_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='system_id',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
    ]
