# Generated by Django 4.2.6 on 2024-05-13 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_employee_lob_alter_employee_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employeeProcess', to='accounts.process'),
        ),
    ]
