# Generated by Django 4.2.6 on 2024-05-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_employee_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pick_drop_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
