# Generated by Django 4.2.6 on 2024-05-27 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_employee_pick_drop_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='avaya_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='doj',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='is_absent',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='is_previously_logged_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='lob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisorLOB', to='accounts.lob'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='pick_drop_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='supervisor_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor1ofSupervisor', to='accounts.supervisor'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='supervisor_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor2ofSupervisor', to='accounts.supervisor'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='vdi',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='N/A', max_length=50, null=True),
        ),
    ]
