# Generated by Django 4.2.6 on 2024-02-18 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShiftLegend',
        ),
    ]
