# Generated by Django 4.2.6 on 2024-02-27 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_employee_avaya_id_employee_doj_employee_vdi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reporting', '0002_delete_shiftlegend'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvayaCDR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_At', models.DateTimeField(auto_now_add=True)),
                ('updated_At', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('time_interval', models.TimeField()),
                ('hour', models.IntegerField(editable=False)),
                ('offer', models.IntegerField()),
                ('answer', models.IntegerField()),
                ('ans_th', models.IntegerField()),
                ('aban_calls', models.IntegerField()),
                ('abn_th', models.IntegerField()),
                ('avg_acd_time', models.FloatField()),
                ('avg_hold_time', models.FloatField()),
                ('avg_acw_time', models.FloatField()),
                ('avg_speed_ans', models.FloatField()),
                ('staffed_time', models.IntegerField()),
                ('acd_time', models.IntegerField()),
                ('acw_time', models.IntegerField()),
                ('hold_time', models.IntegerField()),
                ('avail_time', models.IntegerField()),
                ('aux_time', models.IntegerField()),
                ('agent_ring_time', models.IntegerField()),
                ('other_time', models.IntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avayaCDR_created_by', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avayaCDR_skill', to='accounts.skill')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avayaCDR_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
