# Generated by Django 4.2.6 on 2024-02-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_avayacdr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avayacdr',
            name='aban_calls',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avayacdr',
            name='abn_th',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avayacdr',
            name='acd_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avayacdr',
            name='acw_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avayacdr',
            name='agent_ring_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avayacdr',
            name='ans_th',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avayacdr',
            name='answer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avayacdr',
            name='aux_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avayacdr',
            name='avail_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avayacdr',
            name='avg_acd_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avayacdr',
            name='avg_acw_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avayacdr',
            name='avg_hold_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avayacdr',
            name='avg_speed_ans',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avayacdr',
            name='hold_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avayacdr',
            name='offer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avayacdr',
            name='other_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avayacdr',
            name='staffed_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
