# Generated by Django 4.2.6 on 2024-02-28 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_alter_avayacdr_aban_calls_alter_avayacdr_abn_th_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgentHourlyPerformance',
        ),
    ]
