# Generated by Django 4.2.6 on 2024-02-28 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_employee_avaya_id_employee_doj_employee_vdi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reporting', '0005_delete_agenthourlyperformance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentHourlyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_At', models.DateTimeField(auto_now_add=True)),
                ('updated_At', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('time_interval_start', models.TimeField(blank=True, null=True)),
                ('time_interval_end', models.TimeField(blank=True, null=True)),
                ('hour', models.IntegerField(blank=True, editable=False, null=True)),
                ('hold_time', models.FloatField(blank=True, editable=False, null=True)),
                ('handling_time', models.FloatField(blank=True, editable=False, null=True)),
                ('ready_time', models.FloatField(blank=True, editable=False, null=True)),
                ('acd_calls', models.IntegerField(blank=True, null=True)),
                ('avg_acd_time', models.FloatField(blank=True, null=True)),
                ('avg_acw_time', models.FloatField(blank=True, null=True)),
                ('percent_agent_occup_with_acw', models.IntegerField(blank=True, null=True)),
                ('percent_agent_occup_without_acw', models.IntegerField(blank=True, null=True)),
                ('extn_in_calls', models.IntegerField(blank=True, null=True)),
                ('avg_extn_in_time', models.FloatField(blank=True, null=True)),
                ('extn_out_calls', models.IntegerField(blank=True, null=True)),
                ('avg_extn_out_time', models.FloatField(blank=True, null=True)),
                ('acd_time', models.IntegerField(blank=True, null=True)),
                ('acw_time', models.IntegerField(blank=True, null=True)),
                ('agent_ring_time', models.IntegerField(blank=True, null=True)),
                ('other_time', models.IntegerField(blank=True, null=True)),
                ('aux_time', models.IntegerField(blank=True, null=True)),
                ('avail_time', models.IntegerField(blank=True, null=True)),
                ('percent_skills_avail', models.IntegerField(blank=True, null=True)),
                ('staffed_time', models.IntegerField(blank=True, null=True)),
                ('trans_out', models.IntegerField(blank=True, null=True)),
                ('held_calls', models.IntegerField(blank=True, null=True)),
                ('avg_hold_time', models.FloatField(blank=True, null=True)),
                ('aux_work_on_login', models.IntegerField(blank=True, null=True)),
                ('short_break', models.IntegerField(blank=True, null=True)),
                ('lunch_break', models.IntegerField(blank=True, null=True)),
                ('training', models.IntegerField(blank=True, null=True)),
                ('one_to_one', models.IntegerField(blank=True, null=True)),
                ('meeting', models.IntegerField(blank=True, null=True)),
                ('outbound_callback', models.IntegerField(blank=True, null=True)),
                ('cfs_meeting', models.IntegerField(blank=True, null=True)),
                ('hour_8', models.IntegerField(blank=True, null=True)),
                ('hour_9', models.IntegerField(blank=True, null=True)),
                ('ti_auxtime10', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agentHourlyPerformance_created_by', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agentHourlyPerformance_employee', to='accounts.employee')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentHourlyPerformance_skill', to='accounts.skill')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agentHourlyPerformance_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
