# Generated by Django 4.2.6 on 2024-02-28 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0006_agenthourlyperformance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgentHourlyPerformance',
        ),
    ]
