# Generated by Django 4.2.6 on 2024-03-04 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0025_roster_shiftlegend'),
        ('reporting', '0010_alter_loginlogouttime_logout_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenthourlyperformance',
            name='roster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agentHourlyPerformance_roster', to='roster.roster'),
        ),
    ]
