# Generated by Django 4.2.6 on 2024-03-04 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0025_roster_shiftlegend'),
        ('reporting', '0011_agenthourlyperformance_roster'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenthourlyperformance',
            name='is_absent',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='agenthourlyperformance',
            name='roster',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agentHourlyPerformance_roster', to='roster.roster'),
        ),
    ]
