# Generated by Django 4.2.6 on 2024-03-11 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0012_agenthourlyperformance_is_absent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenthourlyperformance',
            name='is_absent',
        ),
    ]
