# Generated by Django 4.2.6 on 2023-11-30 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_rostercount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rostercount',
            name='count',
        ),
    ]
