# Generated by Django 4.2.6 on 2023-11-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0003_remove_rostercount_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='rostercount',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
