# Generated by Django 4.2.6 on 2023-12-05 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('roster', '0007_totalrostercount'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalrostercount',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='total_roster_count_site', to='accounts.site'),
        ),
    ]
