# Generated by Django 4.2.6 on 2023-12-24 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roster', '0008_totalrostercount_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workRule_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workrule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workRule_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
