# Generated by Django 4.2.6 on 2024-01-02 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roster', '0009_roster_created_by_workrule_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
