# Generated by Django 4.2.6 on 2024-01-23 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roster', '0010_roster_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalrostercount',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='totalRosterCount_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='totalrostercount',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='totalRosterCount_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
