# Generated by Django 4.2.6 on 2024-01-28 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_employee_supervisor_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roster', '0011_totalrostercount_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RosterSeatCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_At', models.DateTimeField(auto_now_add=True)),
                ('updated_At', models.DateTimeField(auto_now=True)),
                ('total', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster_seat_count_created_by', to=settings.AUTH_USER_MODEL)),
                ('lob', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster_seat_count_lob', to='accounts.lob')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster_seat_count_process', to='accounts.process')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster_seat_count_site', to='accounts.site')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster_seat_count_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='TotalRosterCount',
        ),
    ]
