# Generated by Django 4.2.6 on 2024-02-06 11:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_employee_supervisor_1_and_more'),
        ('roster', '0012_rosterseatcount_delete_totalrostercount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_At', models.DateTimeField(auto_now_add=True)),
                ('updated_At', models.DateTimeField(auto_now=True)),
                ('date', models.TimeField()),
                ('interval', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('forecast', models.IntegerField()),
                ('required_hc', models.IntegerField()),
                ('lob', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_lob', to='accounts.lob')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_process', to='accounts.process')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
