# Generated by Django 4.2.6 on 2024-02-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0013_forecast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='date',
            field=models.DateField(),
        ),
    ]
