# Generated by Django 4.2.6 on 2024-02-07 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roster', '0014_alter_forecast_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forecast',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
