# Generated by Django 4.2.6 on 2024-02-14 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_employee_supervisor_1_and_more'),
        ('roster', '0015_forecast_created_by_forecast_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_At', models.DateTimeField(auto_now_add=True)),
                ('updated_At', models.DateTimeField(auto_now=True)),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('acd_calls', models.IntegerField()),
                ('avg_acd_time', models.FloatField()),
                ('avg_acw_time', models.FloatField()),
                ('agent_occupancy_with_acw', models.IntegerField()),
                ('agent_occupancy_without_acw', models.IntegerField()),
                ('extn_in_calls', models.IntegerField()),
                ('avg_extn_in_time', models.FloatField()),
                ('extn_out_calls', models.IntegerField()),
                ('avg_extn_out_time', models.FloatField()),
                ('acd_time', models.BigIntegerField()),
                ('acw_time', models.BigIntegerField()),
                ('agent_ring_time', models.IntegerField()),
                ('other_time', models.IntegerField()),
                ('aux_time', models.BigIntegerField()),
                ('avail_time', models.BigIntegerField()),
                ('staffed_time', models.BigIntegerField()),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acd_employee', to='accounts.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
