# Generated by Django 4.2.6 on 2024-02-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0016_acd'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftLegend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_At', models.DateTimeField(auto_now_add=True)),
                ('updated_At', models.DateTimeField(auto_now=True)),
                ('shift_name', models.CharField(max_length=20)),
                ('shift_count', models.PositiveIntegerField()),
                ('shift_start_time', models.TimeField()),
                ('shift_end_time', models.TimeField()),
                ('login_start_hour', models.PositiveIntegerField()),
                ('duty_hour', models.DurationField()),
                ('target_break', models.DurationField()),
                ('target_ready', models.DurationField()),
                ('hour_0', models.BooleanField(null=True)),
                ('hour_1', models.BooleanField(null=True)),
                ('hour_2', models.BooleanField(null=True)),
                ('hour_3', models.BooleanField(null=True)),
                ('hour_4', models.BooleanField(null=True)),
                ('hour_5', models.BooleanField(null=True)),
                ('hour_6', models.BooleanField(null=True)),
                ('hour_7', models.BooleanField(null=True)),
                ('hour_8', models.BooleanField(null=True)),
                ('hour_9', models.BooleanField(null=True)),
                ('hour_10', models.BooleanField(null=True)),
                ('hour_11', models.BooleanField(null=True)),
                ('hour_12', models.BooleanField(null=True)),
                ('hour_13', models.BooleanField(null=True)),
                ('hour_14', models.BooleanField(null=True)),
                ('hour_15', models.BooleanField(null=True)),
                ('hour_16', models.BooleanField(null=True)),
                ('hour_17', models.BooleanField(null=True)),
                ('hour_18', models.BooleanField(null=True)),
                ('hour_19', models.BooleanField(null=True)),
                ('hour_20', models.BooleanField(null=True)),
                ('hour_21', models.BooleanField(null=True)),
                ('hour_22', models.BooleanField(null=True)),
                ('hour_23', models.BooleanField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
