# Generated by Django 4.2.6 on 2024-02-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0018_shiftlegend_created_by_shiftlegend_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftlegend',
            name='created_At',
        ),
        migrations.RemoveField(
            model_name='shiftlegend',
            name='updated_At',
        ),
        migrations.AlterField(
            model_name='shiftlegend',
            name='duty_hour',
            field=models.DurationField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='shiftlegend',
            name='hour_0',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='shiftlegend',
            name='hour_1',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='shiftlegend',
            name='hour_10',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='shiftlegend',
            name='hour_11',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='shiftlegend',
            name='hour_12',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='shiftlegend',
            name='hour_13',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='shiftlegend',
            name='hour_14',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='shiftlegend',
            name='hour_15',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='shiftlegend',
            name='hour_16',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='shiftlegend',
            name='hour_17',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='shiftlegend',
            name='hour_18',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='shiftlegend',
            name='hour_19',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='shiftlegend',
            name='hour_2',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='shiftlegend',
            name='hour_20',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='shiftlegend',
            name='hour_21',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='shiftlegend',
            name='hour_22',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='shiftlegend',
            name='hour_23',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='shiftlegend',
            name='hour_3',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='shiftlegend',
            name='hour_4',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='shiftlegend',
            name='hour_5',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='shiftlegend',
            name='hour_6',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='shiftlegend',
            name='hour_7',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='shiftlegend',
            name='hour_8',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='shiftlegend',
            name='hour_9',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='shiftlegend',
            name='login_start_hour',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='shiftlegend',
            name='shift_name',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='shiftlegend',
            name='target_break',
            field=models.DurationField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='shiftlegend',
            name='target_ready',
            field=models.DurationField(blank=True, editable=False, null=True),
        ),
    ]
