# Generated by Django 4.2.6 on 2024-02-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0019_remove_shiftlegend_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftlegend',
            name='target_break',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shiftlegend',
            name='target_ready',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
