# Generated by Django 4.2.6 on 2024-02-20 05:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0020_alter_shiftlegend_target_break_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftlegend',
            name='created_At',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shiftlegend',
            name='updated_At',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
