# Generated by Django 4.2.6 on 2024-02-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0021_shiftlegend_created_at_shiftlegend_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftlegend',
            name='shift_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shiftlegend',
            name='shift_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='shiftlegend',
            name='shift_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
