# Generated by Django 4.2.6 on 2024-02-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0022_alter_shiftlegend_shift_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftlegend',
            name='shift_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
