# Generated by Django 4.2.6 on 2024-02-22 05:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0023_alter_shiftlegend_shift_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftlegend',
            name='shift_count',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
