# Generated by Django 4.2.6 on 2024-02-29 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0024_alter_shiftlegend_shift_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='shiftLegend',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rosterShiftLegend', to='roster.shiftlegend'),
        ),
    ]
