# Generated by Django 4.2.6 on 2024-03-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0025_roster_shiftlegend'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='is_absent',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
