# Generated by Django 4.2.6 on 2024-03-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0026_roster_is_absent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='is_absent',
            field=models.IntegerField(blank=True, default=1, editable=False, null=True),
        ),
    ]
