# Generated by Django 4.2.6 on 2024-05-12 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_system_id'),
        ('roster', '0028_alter_shiftlegend_hour_0_alter_shiftlegend_hour_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='N/A', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='roster',
            name='lob',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rosterLOB', to='accounts.lob'),
        ),
        migrations.AddField(
            model_name='roster',
            name='pick_drop_location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='roster',
            name='process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rosterProcess', to='accounts.process'),
        ),
        migrations.AddField(
            model_name='roster',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rosterSite', to='accounts.site'),
        ),
        migrations.AddField(
            model_name='roster',
            name='supervisor_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rosterSupervisor1', to='roster.roster'),
        ),
        migrations.AddField(
            model_name='roster',
            name='supervisor_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rosterSupervisor2', to='roster.roster'),
        ),
        migrations.AddField(
            model_name='roster',
            name='work_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rosterWorkRole', to='accounts.workrole'),
        ),
    ]
